# Generated by Django 4.2.4 on 2023-08-14 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlaylistSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("link", models.CharField(max_length=256, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist", models.CharField(max_length=150)),
                ("title", models.CharField(max_length=150)),
                ("song_link", models.CharField(max_length=150, unique=True)),
                ("album_image", models.URLField()),
                (
                    "playlist_search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="converter.playlistsearch",
                    ),
                ),
            ],
        ),
    ]
