# Generated by Django 4.2.4 on 2023-08-15 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("converter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlistsearch",
            name="link",
            field=models.URLField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="playlist_search",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="converter.playlistsearch",
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="song_link",
            field=models.URLField(max_length=150, unique=True),
        ),
    ]
