# Generated by Django 4.2.4 on 2023-08-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "converter",
            "0002_alter_playlistsearch_link_alter_song_playlist_search_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="playlistsearch",
            name="owner",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="playlistsearch",
            name="playlist_image",
            field=models.URLField(max_length=256, null=True),
        ),
    ]
