# Generated by Django 4.2.4 on 2023-08-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("converter", "0004_remove_song_playlist_search_song_playlist_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlistsearch",
            name="youtube_link",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="song",
            name="youtube_link",
            field=models.URLField(null=True),
        ),
    ]
