# Generated by Django 4.2.4 on 2023-08-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("converter", "0006_playlistsearch_youtube_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="youtube_id",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
