# Generated by Django 4.2.4 on 2023-08-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("converter", "0007_song_youtube_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlistsearch",
            name="title",
            field=models.CharField(default="Untitled", max_length=256),
        ),
    ]
